# Honeywell PrAna Configuration
system:
  update_interval: 2  # seconds
  data_window: 500    # data points to display

# Oven Process Parameters (Honeywell Experion PKS aligned)
process_params:
  heat_zone_1:
    setpoint: 185.0
    operating_range: [180.0, 190.0]
    critical_range: [175.0, 195.0]
  heat_zone_2:
    setpoint: 195.0
    operating_range: [190.0, 200.0]
    critical_range: [185.0, 205.0]
  conveyor_speed:
    setpoint: 2.5
    operating_range: [2.3, 2.7]
    critical_range: [2.0, 3.0]

# ML Model Configuration
model:
  anomaly_threshold: 0.85
  confidence_threshold: 0.92
  retrain_interval: 24  # hours